import "@/styles/globals.css";
import type { Metadata } from "next";
import { Providers } from "./providers";
import { fontSans } from "@/config/fonts";
import clsx from "clsx";
import { NextFont } from "next/dist/compiled/@next/font";
import localFont from "next/font/local"

const myFont1: NextFont = localFont({ src: "../public/fonts/IRANSansWeb.woff" });

export const metadata: Metadata = {
  title: "BPMS",
  description: "Generated by IRISA",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning lang="fa" dir="rtl">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

      </head>
      <body //className={clsx("font-sans antialiased", fontSans.className)}
        className={myFont1.className}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
